List timeZones = [
  {"name": "Afghanistan", "timeZoneName": "Asia/Kabul"},
  {"name": "Albania", "timeZoneName": "Europe/Tirane"},
  {"name": "Algeria", "timeZoneName": "Africa/Algiers"},
  {"name": "Andorra", "timeZoneName": "Europe/Andorra"},
  {"name": "Angola", "timeZoneName": "Africa/Luanda"},
  {"name": "Antigua and Barbuda", "timeZoneName": "America/Antigua"},
  {"name": "Argentina", "timeZoneName": "America/Argentina/Buenos_Aires"},
  {"name": "Armenia", "timeZoneName": "Asia/Yerevan"},
  {"name": "Australia", "timeZoneName": "Australia/Sydney"},
  {"name": "Austria", "timeZoneName": "Europe/Vienna"},
  {"name": "Azerbaijan", "timeZoneName": "Asia/Baku"},
  {"name": "Bahamas", "timeZoneName": "America/Nassau"},
  {"name": "Bahrain", "timeZoneName": "Asia/Bahrain"},
  {"name": "Bangladesh", "timeZoneName": "Asia/Dhaka"},
  {"name": "Barbados", "timeZoneName": "America/Barbados"},
  {"name": "Belarus", "timeZoneName": "Europe/Minsk"},
  {"name": "Belgium", "timeZoneName": "Europe/Brussels"},
  {"name": "Belize", "timeZoneName": "America/Belize"},
  {"name": "Benin", "timeZoneName": "Africa/Porto-Novo"},
  {"name": "Bhutan", "timeZoneName": "Asia/Thimphu"},
  {"name": "Bolivia", "timeZoneName": "America/La_Paz"},
  {"name": "Bosnia and Herzegovina", "timeZoneName": "Europe/Sarajevo"},
  {"name": "Botswana", "timeZoneName": "Africa/Gaborone"},
  {"name": "Brazil", "timeZoneName": "America/Sao_Paulo"},
  {"name": "Brunei", "timeZoneName": "Asia/Brunei"},
  {"name": "Bulgaria", "timeZoneName": "Europe/Sofia"},
  {"name": "Burkina Faso", "timeZoneName": "Africa/Ouagadougou"},
  {"name": "Burundi", "timeZoneName": "Africa/Bujumbura"},
  {"name": "Cabo Verde", "timeZoneName": "Atlantic/Cape_Verde"},
  {"name": "Cambodia", "timeZoneName": "Asia/Phnom_Penh"},
  {"name": "Cameroon", "timeZoneName": "Africa/Douala"},
  {"name": "Canada", "timeZoneName": "America/Toronto"},
  {"name": "Central African Republic", "timeZoneName": "Africa/Bangui"},
  {"name": "Chad", "timeZoneName": "Africa/Ndjamena"},
  {"name": "Chile", "timeZoneName": "America/Santiago"},
  {"name": "China", "timeZoneName": "Asia/Shanghai"},
  {"name": "Colombia", "timeZoneName": "America/Bogota"},
  {"name": "Comoros", "timeZoneName": "Indian/Comoro"},
  {"name": "Congo (Congo-Brazzaville)", "timeZoneName": "Africa/Brazzaville"},
  {"name": "Costa Rica", "timeZoneName": "America/Costa_Rica"},
  {"name": "Croatia", "timeZoneName": "Europe/Zagreb"},
  {"name": "Cuba", "timeZoneName": "America/Havana"},
  {"name": "Cyprus", "timeZoneName": "Asia/Nicosia"},
  {"name": "Czech Republic", "timeZoneName": "Europe/Prague"},
  {"name": "Denmark", "timeZoneName": "Europe/Copenhagen"},
  {"name": "Djibouti", "timeZoneName": "Africa/Djibouti"},
  {"name": "Dominica", "timeZoneName": "America/Dominica"},
  {"name": "Dominican Republic", "timeZoneName": "America/Santo_Domingo"},
  {"name": "Ecuador", "timeZoneName": "America/Guayaquil"},
  {"name": "Egypt", "timeZoneName": "Africa/Cairo"},
  {"name": "El Salvador", "timeZoneName": "America/El_Salvador"},
  {"name": "Equatorial Guinea", "timeZoneName": "Africa/Malabo"},
  {"name": "Eritrea", "timeZoneName": "Africa/Asmara"},
  {"name": "Estonia", "timeZoneName": "Europe/Tallinn"},
  {"name": "Eswatini", "timeZoneName": "Africa/Mbabane"},
  {"name": "Ethiopia", "timeZoneName": "Africa/Addis_Ababa"},
  {"name": "Fiji", "timeZoneName": "Pacific/Fiji"},
  {"name": "Finland", "timeZoneName": "Europe/Helsinki"},
  {"name": "France", "timeZoneName": "Europe/Paris"},
  {"name": "Gabon", "timeZoneName": "Africa/Libreville"},
  {"name": "Gambia", "timeZoneName": "Africa/Banjul"},
  {"name": "Georgia", "timeZoneName": "Asia/Tbilisi"},
  {"name": "Germany", "timeZoneName": "Europe/Berlin"},
  {"name": "Ghana", "timeZoneName": "Africa/Accra"},
  {"name": "Greece", "timeZoneName": "Europe/Athens"},
  {"name": "Grenada", "timeZoneName": "America/Grenada"},
  {"name": "Guatemala", "timeZoneName": "America/Guatemala"},
  {"name": "Guinea", "timeZoneName": "Africa/Conakry"},
  {"name": "Guinea-Bissau", "timeZoneName": "Africa/Bissau"},
  {"name": "Guyana", "timeZoneName": "America/Guyana"},
  {"name": "Haiti", "timeZoneName": "America/Port-au-Prince"},
  {"name": "Honduras", "timeZoneName": "America/Tegucigalpa"},
  {"name": "Hungary", "timeZoneName": "Europe/Budapest"},
  {"name": "Iceland", "timeZoneName": "Atlantic/Reykjavik"},
  {"name": "India", "timeZoneName": "Asia/Kolkata"},
  {"name": "Indonesia", "timeZoneName": "Asia/Jakarta"},
  {"name": "Iran", "timeZoneName": "Asia/Tehran"},
  {"name": "Iraq", "timeZoneName": "Asia/Baghdad"},
  {"name": "Ireland", "timeZoneName": "Europe/Dublin"},
  {"name": "Israel", "timeZoneName": "Asia/Jerusalem"},
  {"name": "Italy", "timeZoneName": "Europe/Rome"},
  {"name": "Jamaica", "timeZoneName": "America/Jamaica"},
  {"name": "Japan", "timeZoneName": "Asia/Tokyo"},
  {"name": "Jordan", "timeZoneName": "Asia/Amman"},
  {"name": "Kazakhstan", "timeZoneName": "Asia/Almaty"},
  {"name": "Kenya", "timeZoneName": "Africa/Nairobi"},
  {"name": "Kiribati", "timeZoneName": "Pacific/Tarawa"},
  {"name": "Kuwait", "timeZoneName": "Asia/Kuwait"},
  {"name": "Kyrgyzstan", "timeZoneName": "Asia/Bishkek"},
  {"name": "Laos", "timeZoneName": "Asia/Vientiane"},
  {"name": "Latvia", "timeZoneName": "Europe/Riga"},
  {"name": "Lebanon", "timeZoneName": "Asia/Beirut"},
  {"name": "Lesotho", "timeZoneName": "Africa/Maseru"},
  {"name": "Liberia", "timeZoneName": "Africa/Monrovia"},
  {"name": "Libya", "timeZoneName": "Africa/Tripoli"},
  {"name": "Liechtenstein", "timeZoneName": "Europe/Vaduz"},
  {"name": "Lithuania", "timeZoneName": "Europe/Vilnius"},
  {"name": "Luxembourg", "timeZoneName": "Europe/Luxembourg"},
  {"name": "Madagascar", "timeZoneName": "Indian/Antananarivo"},
  {"name": "Malawi", "timeZoneName": "Africa/Blantyre"},
  {"name": "Malaysia", "timeZoneName": "Asia/Kuala_Lumpur"},
  {"name": "Maldives", "timeZoneName": "Indian/Maldives"},
  {"name": "Mali", "timeZoneName": "Africa/Bamako"},
  {"name": "Malta", "timeZoneName": "Europe/Malta"},
  {"name": "Marshall Islands", "timeZoneName": "Pacific/Majuro"},
  {"name": "Martinique", "timeZoneName": "America/Martinique"},
  {"name": "Mauritania", "timeZoneName": "Africa/Nouakchott"},
  {"name": "Mauritius", "timeZoneName": "Indian/Mauritius"},
  {"name": "Mexico", "timeZoneName": "America/Mexico_City"},
  {"name": "Micronesia (Federated States of)", "timeZoneName": "Pacific/Chuuk"},
  {"name": "Moldova, Republic of", "timeZoneName": "Europe/Chisinau"},
  {"name": "Monaco", "timeZoneName": "Europe/Monaco"},
  {"name": "Mongolia", "timeZoneName": "Asia/Ulaanbaatar"},
  {"name": "Montenegro", "timeZoneName": "Europe/Podgorica"},
  {"name": "Montserrat", "timeZoneName": "America/Montserrat"},
  {"name": "Morocco", "timeZoneName": "Africa/Casablanca"},
  {"name": "Mozambique", "timeZoneName": "Africa/Maputo"},
  {"name": "Myanmar", "timeZoneName": "Asia/Yangon"},
  {"name": "Namibia", "timeZoneName": "Africa/Windhoek"},
  {"name": "Nauru", "timeZoneName": "Pacific/Nauru"},
  {"name": "Nepal", "timeZoneName": "Asia/Kathmandu"},
  {"name": "Netherlands", "timeZoneName": "Europe/Amsterdam"},
  {"name": "New Caledonia", "timeZoneName": "Pacific/Noumea"},
  {"name": "New Zealand", "timeZoneName": "Pacific/Auckland"},
  {"name": "Nicaragua", "timeZoneName": "America/Managua"},
  {"name": "Niger", "timeZoneName": "Africa/Niamey"},
  {"name": "Nigeria", "timeZoneName": "Africa/Lagos"},
  {"name": "Niue", "timeZoneName": "Pacific/Niue"},
  {"name": "Norfolk Island", "timeZoneName": "Pacific/Norfolk"},
  {"name": "North Macedonia", "timeZoneName": "Europe/Skopje"},
  {"name": "Northern Mariana Islands", "timeZoneName": "Pacific/Saipan"},
  {"name": "Norway", "timeZoneName": "Europe/Oslo"},
  {"name": "Oman", "timeZoneName": "Asia/Muscat"},
  {"name": "Pakistan", "timeZoneName": "Asia/Karachi"},
  {"name": "Palau", "timeZoneName": "Pacific/Palau"},
  {"name": "Palestine, State of", "timeZoneName": "Asia/Gaza"},
  {"name": "Panama", "timeZoneName": "America/Panama"},
  {"name": "Papua New Guinea", "timeZoneName": "Pacific/Port_Moresby"},
  {"name": "Paraguay", "timeZoneName": "America/Asuncion"},
  {"name": "Peru", "timeZoneName": "America/Lima"},
  {"name": "Philippines", "timeZoneName": "Asia/Manila"},
  {"name": "Poland", "timeZoneName": "Europe/Warsaw"},
  {"name": "Portugal", "timeZoneName": "Europe/Lisbon"},
  {"name": "Puerto Rico", "timeZoneName": "America/Puerto_Rico"},
  {"name": "Qatar", "timeZoneName": "Asia/Qatar"},
  {"name": "Romania", "timeZoneName": "Europe/Bucharest"},
  {"name": "Russian Federation", "timeZoneName": "Europe/Moscow"},
  {"name": "Rwanda", "timeZoneName": "Africa/Kigali"},
  {"name": "Réunion", "timeZoneName": "Indian/Reunion"},
  {"name": "Saint Barthélemy", "timeZoneName": "America/St_Barthelemy"},
  {
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "timeZoneName": "Atlantic/St_Helena"
  },
  {"name": "Saint Kitts and Nevis", "timeZoneName": "America/St_Kitts"},
  {"name": "Saint Lucia", "timeZoneName": "America/St_Lucia"},
  {"name": "Saint Martin (French part)", "timeZoneName": "America/Marigot"},
  {"name": "Saint Pierre and Miquelon", "timeZoneName": "America/Miquelon"},
  {
    "name": "Saint Vincent and the Grenadines",
    "timeZoneName": "America/St_Vincent"
  },
  {"name": "Samoa", "timeZoneName": "Pacific/Apia"},
  {"name": "San Marino", "timeZoneName": "Europe/San_Marino"},
  {"name": "Sao Tome and Principe", "timeZoneName": "Africa/Sao_Tome"},
  {"name": "Saudi Arabia", "timeZoneName": "Asia/Riyadh"},
  {"name": "Senegal", "timeZoneName": "Africa/Dakar"},
  {"name": "Serbia", "timeZoneName": "Europe/Belgrade"},
  {"name": "Seychelles", "timeZoneName": "Indian/Mahe"},
  {"name": "Sierra Leone", "timeZoneName": "Africa/Freetown"},
  {"name": "Singapore", "timeZoneName": "Asia/Singapore"},
  {
    "name": "Sint Maarten (Dutch part)",
    "timeZoneName": "America/Lower_Princes"
  },
  {"name": "Slovakia", "timeZoneName": "Europe/Bratislava"},
  {"name": "Slovenia", "timeZoneName": "Europe/Ljubljana"},
  {"name": "Solomon Islands", "timeZoneName": "Pacific/Guadalcanal"},
  {"name": "Somalia", "timeZoneName": "Africa/Mogadishu"},
  {"name": "South Africa", "timeZoneName": "Africa/Johannesburg"},
  {"name": "South Sudan", "timeZoneName": "Africa/Juba"},
  {"name": "Spain", "timeZoneName": "Europe/Madrid"},
  {"name": "Sri Lanka", "timeZoneName": "Asia/Colombo"},
  {"name": "Sudan", "timeZoneName": "Africa/Khartoum"},
  {"name": "Suriname", "timeZoneName": "America/Paramaribo"},
  {"name": "Sweden", "timeZoneName": "Europe/Stockholm"},
  {"name": "Switzerland", "timeZoneName": "Europe/Zurich"},
  {"name": "Syrian Arab Republic", "timeZoneName": "Asia/Damascus"},
  {"name": "Taiwan, Province of China", "timeZoneName": "Asia/Taipei"},
  {"name": "Tajikistan", "timeZoneName": "Asia/Dushanbe"},
  {
    "name": "Tanzania, United Republic of",
    "timeZoneName": "Africa/Dar_es_Salaam"
  },
  {"name": "Thailand", "timeZoneName": "Asia/Bangkok"},
  {"name": "Timor-Leste", "timeZoneName": "Asia/Dili"},
  {"name": "Togo", "timeZoneName": "Africa/Lome"},
  {"name": "Tokelau", "timeZoneName": "Pacific/Fakaofo"},
  {"name": "Tonga", "timeZoneName": "Pacific/Tongatapu"},
  {"name": "Trinidad and Tobago", "timeZoneName": "America/Port_of_Spain"},
  {"name": "Tunisia", "timeZoneName": "Africa/Tunis"},
  {"name": "Turkey", "timeZoneName": "Europe/Istanbul"},
  {"name": "Turkmenistan", "timeZoneName": "Asia/Ashgabat"},
  {"name": "Tuvalu", "timeZoneName": "Pacific/Funafuti"},
  {"name": "Uganda", "timeZoneName": "Africa/Kampala"},
  {"name": "Ukraine", "timeZoneName": "Europe/Kiev"},
  {"name": "United Arab Emirates", "timeZoneName": "Asia/Dubai"},
  {
    "name": "United Kingdom of Great Britain and Northern Ireland",
    "timeZoneName": "Europe/London"
  },
  {
    "name": "United States Minor Outlying Islands",
    "timeZoneName": "Pacific/Midway"
  },
  {"name": "United States of America", "timeZoneName": "America/New_York"},
  {"name": "Uruguay", "timeZoneName": "America/Montevideo"},
  {"name": "Uzbekistan", "timeZoneName": "Asia/Tashkent"},
  {"name": "Vanuatu", "timeZoneName": "Pacific/Efate"},
  {
    "name": "Venezuela (Bolivarian Republic of)",
    "timeZoneName": "America/Caracas"
  },
  {"name": "Viet Nam", "timeZoneName": "Asia/Ho_Chi_Minh"},
  {"name": "Wallis and Futuna", "timeZoneName": "Pacific/Wallis"},
  {"name": "Western Sahara", "timeZoneName": "Africa/El_Aaiun"},
  {"name": "Yemen", "timeZoneName": "Asia/Aden"},
  {"name": "Zambia", "timeZoneName": "Africa/Lusaka"},
  {"name": "Zimbabwe", "timeZoneName": "Africa/Harare"}
];
